node {
    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        echo 'Build your ruby application...'
    }

    stage('Test') {
        try {
            sh 'npm run ci-test'
        } finally { junit 'build/reports/**/*.xml' }
    }

    stage('Deploy') { echo 'Deploying!' }

    stage('Promote') { echo 'Promote!' }
}