Feature: Demonstrate Docstrings

Scenario: Using a Docstring Parameter
    Given some multiline text is typed into the screen:
      """
      line 1...
      line 2...
      line 3...
      more....
      """