library 'common-lib'

node {
    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        echo 'Build your nodejs application...'
    }

    stage('Test') {
        try {
            tests.executeCucumberTests([
                language: 'javascript'
            ])
        } finally { junit 'build/reports/**/*.xml' }
    }

    stage('Deploy') { echo 'Deploying!' }

    stage('Promote') { echo 'Promote!' }
}