node {
    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        echo 'Build your ruby application...'
    }

    stage('Test') {
        sh 'rake ci'
    }

    stage('Deploy') { echo 'Deploying!' }

    stage('Promote') { echo 'Promote!' }
}